"""Stable machine-readable error codes."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Initial public error-code contract."""

    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    SECRET_RESOLUTION_ERROR = "SECRET_RESOLUTION_ERROR"
    CONNECTION_ERROR = "CONNECTION_ERROR"
    CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
    DATABASE_OPERATION_ERROR = "DATABASE_OPERATION_ERROR"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    SAFETY_POLICY_ERROR = "SAFETY_POLICY_ERROR"
    POLICY_DENIED = "POLICY_DENIED"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    AUDIT_UNAVAILABLE = "AUDIT_UNAVAILABLE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
