"""Drift guard for the LOT-20 public Python API inventory."""

from importlib import import_module

import pytest

pytestmark = pytest.mark.unit

EXPECTED_PUBLIC_EXPORTS: dict[str, set[str]] = {
    "pydbadminkit": {"__version__"},
    "pydbadminkit.domain.common": {
        "CapabilityAvailability",
        "CapabilityStatus",
        "DatabaseEngine",
        "DatabaseObjectRef",
        "DatabaseObjectType",
        "DatabaseVersion",
        "EnvironmentName",
        "OperationResult",
        "OperationStatus",
        "QualifiedName",
        "RiskLevel",
        "parse_qualified_name",
    },
    "pydbadminkit.domain.connection": {
        "ConnectionProfile",
        "ConnectionProfileName",
        "ConnectionTestResult",
        "ResolvedConnectionConfig",
        "SSLConfig",
        "SSLMode",
        "SecretReference",
        "SecretValue",
        "TimeoutConfig",
    },
    "pydbadminkit.domain.catalog": {
        "ColumnInfo",
        "ConstraintInfo",
        "ConstraintType",
        "DatabaseInfo",
        "IndexDescription",
        "IndexInfo",
        "SchemaInfo",
        "ServerInfo",
        "TableDescription",
        "TableInfo",
        "TableKind",
        "ViewDescription",
        "ViewInfo",
        "ViewKind",
    },
    "pydbadminkit.domain.security": {
        "AccessSource",
        "AccessType",
        "AlterRoleCommand",
        "CreateRoleCommand",
        "DirectAccess",
        "EffectiveAccess",
        "MembershipCommand",
        "OwnershipInfo",
        "RelationAccessCommand",
        "RoleDescription",
        "RoleInfo",
        "RoleMembership",
    },
    "pydbadminkit.domain.runtime": {
        "BackendSignalResult",
        "BlockingRelation",
        "CancelQueryCommand",
        "LockInfo",
        "QueryInfo",
        "SessionInfo",
        "SessionState",
        "TerminateSessionCommand",
        "TransactionInfo",
        "WaitInfo",
    },
    "pydbadminkit.domain.operations": {
        "AnalyzeCommand",
        "Backup",
        "BackupArtifactInfo",
        "BackupFormat",
        "BackupMetadata",
        "BackupPaths",
        "BackupToolResult",
        "BackupValidation",
        "CreateBackupCommand",
        "ExternalTool",
        "MaintenanceOperation",
        "MaintenanceOperationType",
        "MaintenanceProgress",
        "ProcessResult",
        "ReindexCommand",
        "ReindexTargetType",
        "RestoreBackupCommand",
        "RestoreOperation",
        "RestoreValidation",
        "VacuumCommand",
    },
    "pydbadminkit.domain.monitoring": {
        "CORE_METRIC_DESCRIPTORS",
        "CORE_METRIC_REGISTRY",
        "DEFAULT_EXPORT_LABELS",
        "FORBIDDEN_EXPORT_LABELS",
        "INTERNAL_METRIC_PREFIX",
        "PROMETHEUS_METRIC_PREFIX",
        "ConnectionStatistics",
        "DatabaseSizeMetric",
        "HealthCheckCategory",
        "HealthCheckEvidence",
        "HealthCheckResult",
        "HealthReport",
        "HealthStatus",
        "IndexStatistics",
        "Metric",
        "MetricCardinalityPolicy",
        "MetricDescriptor",
        "MetricType",
        "MonitoringSnapshot",
        "TableSizeMetric",
        "TableStatistics",
        "Threshold",
        "internal_metric_name",
        "prometheus_metric_name",
        "validate_metric_name",
    },
    "pydbadminkit.application.capability": {"CapabilityService"},
    "pydbadminkit.application.catalog": {"CatalogService"},
    "pydbadminkit.application.connection": {
        "ConnectionConfigResolver",
        "ConnectionService",
    },
    "pydbadminkit.application.operations": {
        "BackupService",
        "BackupValidationService",
        "MaintenanceService",
        "RestoreService",
    },
    "pydbadminkit.application.runtime": {
        "RuntimeMutationService",
        "RuntimeService",
    },
    "pydbadminkit.application.security": {
        "SecurityMutationService",
        "SecurityService",
    },
    "pydbadminkit.application.server": {"ServerService"},
    "pydbadminkit.application.monitoring": {
        "HealthCheckConfig",
        "HealthCheckRunner",
        "HealthService",
        "MetricExportService",
        "MonitoringService",
        "MonitoringSnapshotService",
    },
    "pydbadminkit.ports": {
        "AuditPort",
        "BackupFileStorePort",
        "BackupPort",
        "CapabilityPort",
        "CatalogPort",
        "ConfigRepositoryPort",
        "ConnectionTesterPort",
        "MaintenancePort",
        "MetricExporterPort",
        "MonitoringPort",
        "ProcessRunnerPort",
        "RestoreDatabasePort",
        "RestorePort",
        "RuntimeMutationPort",
        "RuntimePort",
        "SecretProviderPort",
        "SecurityMutationPort",
        "SecurityPort",
        "ServerPort",
        "ToolResolverPort",
    },
    "pydbadminkit.errors": {
        "AuditUnavailableError",
        "AuthenticationError",
        "AuthorizationError",
        "BackupError",
        "BackupValidationError",
        "CapabilityNotAvailableError",
        "ChecksumMismatchError",
        "ConfigurationError",
        "ConfirmationRequiredError",
        "DatabaseConnectionError",
        "DatabaseConnectionTimeoutError",
        "DatabaseOperationError",
        "ExternalToolError",
        "FileCollisionError",
        "InternalError",
        "MaintenanceError",
        "OperationTimeoutError",
        "PolicyDeniedError",
        "ProfileNotFoundError",
        "PyDBAdminError",
        "ResourceAlreadyExistsError",
        "ResourceNotFoundError",
        "RestoreError",
        "RestoreValidationError",
        "SafetyPolicyError",
        "SecretResolutionError",
        "ToolExecutionError",
        "ToolNotFoundError",
        "ToolVersionMismatchError",
        "UnsafePathError",
        "ValidationError",
    },
}


@pytest.mark.parametrize("module_name", sorted(EXPECTED_PUBLIC_EXPORTS))
def test_public_package_exports_match_inventory(module_name: str) -> None:
    module = import_module(module_name)

    assert set(module.__all__) == EXPECTED_PUBLIC_EXPORTS[module_name]
