name: Unit Tests

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: python -m pip install --upgrade pip
      - run: pip install -e ".[dev,binary]"
      - run: pytest -m unit --cov=pydbadminkit --cov-report=term-missing --cov-report=xml
